name: Deploy to VPS via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Debian VPS via SSH and run deploy.sh
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd "/root/papayoo-counter/papyoo-counter"
            ./deploy.sh
